Omit the need to call all modifiers.
openscholar/purl-d8 pull request #11
Opened 2020-09-14 11:15 UTC by uttkarsh-26

https://github.com/openscholar/openscholar/issues/14405

2020-09-14 12:30 UTC, rbran100 requested changes
I agree with the path you are taking, but any caching probably needs to happen in the group_purl code, you might still be able to fit your pattern.

2020-09-14 12:30 UTC, rbran100 commented on src/Event/RequestSubscriber.php
> +    $provider = Provider::load(self::GROUP_PURL_PROVIDER);
We can not just call the GROUP_PURL_PROVIDER as we will soon have multiple providers for domain in addition to path prefix, also purl should not be dependent on group_purl.

2020-09-14 12:30 UTC, rbran100 commented on src/Event/RequestSubscriber.php
> +      $modifier = $provider_plugin->getModifierDataByKey($uri);
The uri will not always be the key for all providers/modifiers, the providers will need the entire request to make their determination.

2020-09-14 12:53 UTC, uttkarsh-26 commented
> I agree with the path you are taking, but any caching probably needs to happen in the group_purl code, you might still be able to fit your pattern.

I also doubted it that's why thought to get validation on this. anyways will see something else tomorrow in the same direction.

2020-09-15 13:25 UTC, uttkarsh-26 commented on src/Plugin/ModifierIndex.php
> +    if (method_exists($provider->getProviderPlugin(), 'getModifierDataByKey')) {
still need this I think, because inside the if it calls `getModifierDataByKey`

2020-09-16 16:51 UTC, merged